apiVersion: v1
kind: Service
metadata:
  name: random-number-generator
spec:
  selector:
    app: random-number-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort